# Generated by Django 4.1.5 on 2023-04-11 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Removecash',
            fields=[
                ('cash_id', models.AutoField(primary_key=True, serialize=False)),
                ('cash_amount', models.IntegerField()),
                ('cash_type', models.CharField(max_length=15)),
                ('cash_desc', models.CharField(max_length=500)),
            ],
        ),
    ]
