# Generated by Django 4.1.5 on 2023-04-11 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_removecash'),
    ]

    operations = [
        migrations.CreateModel(
            name='futureExpense',
            fields=[
                ('exp_id', models.AutoField(primary_key=True, serialize=False)),
                ('exp_amt', models.IntegerField()),
                ('exp_desc', models.CharField(max_length=500)),
            ],
        ),
    ]
