# Generated by Django 4.1.5 on 2023-04-11 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_futureexpense'),
    ]

    operations = [
        migrations.AddField(
            model_name='futureexpense',
            name='exp_type',
            field=models.CharField(default='note', max_length=15),
        ),
    ]
